### ISSUE TITLE
Discrepancy between `/metadata` curated count and `/query` count

### ISSUE THREAD

**Issue by vincerubinetti** [biothings/mygeneset.info#47] opened 2022-06-13 21:17 UTC
Per https://mygeneset.info/v1/metadata, there are `195647` curated genesets and `195650` total genesets. Per https://mygeneset.info/v1/query?q=_exists_:source there are `146961 ` curated genesets. Per https://mygeneset.info/v1/query there are `146964` total genesets.

The differences of `3` make sense because there are only 3 user-created genesets at the moment, all created by `ravila4`.

Motivation for this question: 

Here I'm using the `/metadata` info for numbers:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8326331/173447036-a704e015-bd64-4c22-b26d-4008800a02e4.png">

But here I'm using `/query` for numbers (note the very bottom under the table):
<img width="699" alt="image" src="https://user-images.githubusercontent.com/8326331/173446851-e6c336b9-a094-4075-ad46-3be32cdb1032.png">

I'd like them to match.

**Comment by ravila4** [comment] 2022-06-28 21:45
Not sure, what is the cause of this, but I will check if there is still a discrepancy after the next data update.

**Comment by ravila4** [comment] 2022-09-10 03:52
This issue seems to be fixed in the latest data release.
I think it was caused by some documents from the `smpdb` data source that were  missing the 'is_public' field, so they didn't show up in queries.

**Closed** 2022-09-10 03:52 UTC
